services:
  # Service: Gateway
  gateway_service:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gateway_service:/app  # Монтируем локальную директорию в контейнер
    env_file:
      - .env    # Указываем файл с переменными окружения
    networks:
      - app_network
    depends_on:
      - llm_service
    
  # Service: LLM
  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./llm_service:/app  
    env_file:
      - .env  
    networks:
      - app_network

  tg_bot:
    build: 
      context: ./tg_bot
      dockerfile: Dockerfile
    volumes:
      - ./tg_bot:/app
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
