services:
  gateway_service:
    build:
      context: ./gateway_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./gateway_service:/app 
    env_file:
      - .env   
    networks:
      - app_network
    depends_on:
      - llm_service
    
  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./llm_service:/app  
    env_file:
      - .env  
    networks:
      - app_network


networks:
  app_network:
    external: true
