name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  

jobs:
  deploy:
    name: Deploy && Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Gateway Service
        uses: docker/build-push-action@v3
        with:
          context: ./gateway_service
          file: ./gateway_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gateway_service:latest
          
      - name: Build and Push LLM Service
        uses: docker/build-push-action@v3
        with:
          context: ./llm_service
          file: ./llm_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/llm_service:latest