name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy && Push Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Cache Docker layers for Gateway Service
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-gateway-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gateway-
          
      - name: Build and Push Gateway Service
        uses: docker/build-push-action@v3
        with:
          context: ./gateway_service
          file: ./gateway_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/gateway_service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/gateway_service:latest
          cache-to: type=local,dest=~/.docker/buildx-cache

      - name: Cache Docker layers for LLM Service
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-llm-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-llm-

      - name: Build and Push LLM Service
        uses: docker/build-push-action@v3
        with:
          context: ./llm_service
          file: ./llm_service/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/llm_service:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/llm_service:latest
          cache-to: type=local,dest=~/.docker/buildx-cache

      - name: Cache Docker layers for Telegram Bot
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-tg-bot-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-tg-bot-

      - name: Build and Push Telegram Bot
        uses: docker/build-push-action@v3
        with:
          context: ./tg_bot
          file: ./tg_bot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tg_bot:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/tg_bot:latest
          cache-to: type=local,dest=~/.docker/buildx-cache
